from config import BIRTH_NAME, CITY, COMMON_NAME, DATE_OF_BIRTH, FIRST_NAME, GENDER, NUMBER, POLLING_STATION, STREET, ZIP 

rename_column = {
    "LieuDit":"lieu-dit",
    "libellé de voie": STREET,
    "Libellé voie": STREET,
    "LibelleVoie": STREET,
    "libelle de voie": STREET,
    "Num.voie": NUMBER,
    "numéro de voie": NUMBER,
    "numero de voie": NUMBER,
    "NumeroVoie": NUMBER,
    "libelle de l'ugle": CITY,
    "libellé de l'ugle": CITY,
    "Code postal": ZIP,
    "code postal": ZIP,
    "Code Postal": ZIP,
    "code du bureau de vote": POLLING_STATION,
    "NoBureauDeVote": POLLING_STATION,
    "Bureau de vote": POLLING_STATION,
    "Bureau": POLLING_STATION,
    "Date de Naissance": DATE_OF_BIRTH,
    "Date de naissance": DATE_OF_BIRTH,
    "date naissance": DATE_OF_BIRTH,
    "date": DATE_OF_BIRTH,
    "DATE": DATE_OF_BIRTH,
    "Nom usage": COMMON_NAME,
    "Nom d'Usage": COMMON_NAME,
    "nom d'usage": COMMON_NAME,
    "NomDusage": COMMON_NAME,
    "nom de naissance": BIRTH_NAME,
    "NomdeNaissance": BIRTH_NAME,
    "Prénoms": FIRST_NAME,
    "Prénom": FIRST_NAME,
    "prénoms": FIRST_NAME,
    "prenom": FIRST_NAME,
    "prenoms": FIRST_NAME,
    "Sexe": GENDER,
    
}
