rename_column = {
    "numéro de voie": "numero",
    "NumeroVoie": "numero",
    "commune": "ville",
    "code du bureau de vote": "numero bv",
    "NoBureauDeVote": "numero bv",
    "libellé de voie": "rue",
    "LibelleVoie": "rue",
    "code postal": "cp",
    "date de naissance": "date",
    "nom d'usage": "nomUsage",
    "NomDusage": "nomUsage",
    "nom de naissance": "nomNaissance",
    "NomdeNaissance": "nomNaissance",
    "prénoms": "prenom",
    "LieuDit":"lieu-dit",
}
